### ISSUE TITLE
Failures on master

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/citgm#518]
Just finished doing an audit of citgm runs for 9.x and master

All 9.x failures are now accounted for and updated.

There are three modules failing on master for *nix that need to be looked into

* [ava](https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1124/nodes=osx1010/testReport/(root)/citgm/ava_v0_24_0/)
  - dug in and there are legit failures
* [eslint](https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1124/nodes=osx1010/testReport/(root)/citgm/eslint_v4_12_1/)
* [gulp](https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1124/nodes=osx1010/testReport/(root)/citgm/gulp_v3_9_1/)

**Comment by MylesBorins** [comment]
@refack is digging into the failures on windows, which have a few additional failures not seen on other platforms

**Comment by refack** [comment]
On Windows we have similar failures in:
* `eslint-v4.12.1`

Unique:
* `iconv-v2.3.0` - digging further

Infra:
* `lodash-v4.17.4`
* `bson-v1.0.4`
  ```
  Error: EPERM: operation not permitted, scandir ...
  ```

`spawn-wrap` related:
* `sax-v1.2.4`
* `semver-v5.4.1`
  ```
  module.js:561
     throw err;
     ^
  Error: Cannot find module 'C:\Users\Administrator\.node-spawn-wrap-4160-83374712ed52\node.EXE'
  ```

**Comment by refack** [comment]
`iconv` fail does not reproduce when run manually, so I assume it's also infra related (TTY streams in Jenkins are multiple manipulated java->MSYS->npm->node->iconv)

```
assert.js:42
   throw new errors.AssertionError({
   ^
 AssertionError [ERR_ASSERTION]: 'ï¿½\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001' == '+AOc-x+AOc-'
     at Socket.<anonymous> (C:\Users\ADMINI~1\AppData\Local\Temp\1\6892bcce-9354-4db5-8fa0-eb2ab5cee83b\iconv\test\test-stream.js:65:14)
     at Socket.emit (events.js:126:13)
     at addChunk (_stream_readable.js:265:12)
     at readableAddChunk (_stream_readable.js:248:13)
     at Socket.Readable.push (_stream_readable.js:209:10)
     at TCP.onread (net.js:608:20)
```

/CC @bnoordhuis

**Comment by addaleax** [comment]
I tried to look into `eslint` – `rm -rf node_modules && npm install` did the trick for me, weirdly enough

`gulp` is due to `natives` being broken by https://github.com/nodejs/node/pull/13295

**Comment by BridgeAR** [comment]
This seems outdated and got superseded by #558

It should therefore be closed.
