### PR TITLE
lookup: unskip uglify-js

### PR DESCRIPTION
**Pull request by gdams**
uglify-js seems to be passing now and I have also removed the flaky tag
for darwin

##### Checklist

- [x] `npm test` passes
- [x] contribution guidelines followed [here](https://github.com/nodejs/citgm/blob/master/CONTRIBUTING.md)
- [x] commit message follows commit guidelines

### CODE REVIEW

**Comment by gdams** [comment]
v4: https://ci.nodejs.org/view/Node.js-citgm/job/gibfahn-citgm-smoker-more-platforms/112/
v6: https://ci.nodejs.org/view/Node.js-citgm/job/gibfahn-citgm-smoker-more-platforms/113/
v7: https://ci.nodejs.org/view/Node.js-citgm/job/gibfahn-citgm-smoker-more-platforms/114

**Comment by gibfahn** [comment]
Looks like `uglify-js` was skipped in https://github.com/nodejs/citgm/pull/305, failure given was:

```
Error: Cannot find module 'cliui'
```

Doesn't seem to be happening any more, so we should be good to re-enable.

**Comment by gdams** [comment]
we are still seeing the failure from #305 on v7. We should add a skip for just v7

**Comment by gdams** [comment]
Okay so I have added a flaky tag for v7

**Comment by gdams** [comment]
CC @mishoo any idea why we are seeing `Error: Cannot find module 'cliui'` on V7?

**Comment by MylesBorins** [comment]
@gdams this is an npm problem if I recall

**Comment by gdams** [comment]
v6 re-run: https://ci.nodejs.org/view/Node.js-citgm/job/gibfahn-citgm-smoker-more-platforms/115/

**Comment by gdams** [comment]
@gibfahn rhel-s390 passed on the re-run of v6, looks like a machine issue caused the timeout bnefore
